FROM python:3.12.0-slim

WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY data_layer data_layer
COPY api api
ENV PYTHONPATH=${PYTHONPATH}:${PWD}

CMD ["uvicorn", "api.main:api", "--host", "0.0.0.0", "--port", "8000"]
