FROM python:3.12.0-slim

WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /code/data
COPY data/dataset_gps.csv /code/data/dataset_gps.csv
COPY gps_replay gps_replay
COPY scripts/replay_to_redis_cache.py /code/replay_to_redis_cache.py
ENV PYTHONPATH=${PYTHONPATH}:${PWD}

CMD ["python", "replay_to_redis_cache.py"]
