version: '3.3'

services:
  data_player:
    build:
      context: .
      dockerfile: ./dockerfile.replayer_pub
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: ./dockerfile.app
      args:
        - DATA_SOURCE=pub_sub
    ports:
      - '8501:8501'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - data_player
